### ISSUE TITLE
Game is buggy on MacOS

### ISSUE THREAD

**Issue by AnastasiusVivaldus** [flightcrank/asteroids#1]
Maybe this isn't the point of the repo, but the game is pretty buggy. As soon as I die I don't return and my lives eventually just disappear. I also have to kill the game forcefully to finish. Is buggines like this to be expected due to e.g. minimal effort to port it?

**Comment by flightcrank** [comment]
- Its not a port, it was just a recreation. 
- Its not really a bug that your lives disappear thats just the end of the game.
- just press esc to quit. (its in the readme)

source is open so feel free to add a scoring system. game over screen, more lives etc.
